version: "2"
services:
  web:
    build: .
    ports: 
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - .:/
  db:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    env_file:
      - production.env
