version: '3'
services:
  rawleydotxyz:
    build:
      context: .
    restart: unless-stopped
    volumes:
      - '.:/rawleydotxyz'
    ports:
      - '8080:8080'
    links:
      - db
    depends_on:
      - db
  
  db:
    image: mariadb:10.7.4
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_MYSQL_LOCALHOST_USER: ${DB_USER}
    volumes:
      - './dump.sql:/docker-entrypoint-initdb.d/dump.sql'
    restart: always
    expose: ['3306']
