version: '3'
services:
  rawleydotxyz:
    build:
      context: .
    restart: unless-stopped
    volumes:
      - '.:/rawleydotxyz'
    ports:
      - '8080:8080'
  
  db:
    image: mariadb:10.7.4
    volumes:
      - './dump.sql:/docker-entrypoint-initdb.d/dump.sql'
    restart: always
    expose: ['3306']
