version: '3'
services:
  rawleydotxyz:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8080:8080"
  
  db:
    image: mariadb:apline
    restart: always
    expose: ["3306"]
