version: "2"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/sites-enabled/rawleydotxyz.conf:/etc/nginx/sites-available/rawleydotxyz.conf
  web:
    container_name: web
    build: .
    ports: 
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - .:/var/www/rawleydotxyz
    links:
      - db
  db:
    container_name: mysql
    image: "mysql:5.7"
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    env_file:
      - production.env
volumes:
  mysql-db:
